### ISSUE TITLE
[Bug] ./t and ./towny perms aren't configured

### ISSUE THREAD

**Issue by hexxferret** [TheAxisNetwork/Axis-Support#3]
**Top is for bug and error reports, bottom for feature requests. Please use only one, and delete the other.**

------------
### Expected Behavior
Explain how you think it should work.
./t new should create a town
### Actual Behavior
How it actually behaves.
You dont have enough permissions for that command
### How to Reproduce Issue
Explaination of how to reproduce the issue.
Try ./t new on a citizen ranked account
### User Classification
Citizen Rank
------------
### Feature Requested
Shortly explain the feature you're requesting.

### Why?
Explain why you want this feature added.

**Comment by TheFlagCourier** [comment]
Issue should be resolved. Will close when we can confirm with a **Helper** to test.

**Comment by TheFlagCourier** [comment]
Tested with Breezeified, problem resolved.
