### ISSUE TITLE
Bug in hub

### ISSUE THREAD

**Issue by Pro-Killer-2184-aka-Halfkrafted** [TheAxisNetwork/Axis-Support#4]
### Expected Behavior
Explain how you think it should work.
Barrier should be placed in a certain place
### Actual Behavior
How it actually behaves.
You can get outside of the hub
### How to Reproduce Issue
Explaination of how to reproduce the issue.
By parkouring your way up
### User Classification
video https://www.youtube.com/watch?v=cVZI80wqLVw&feature=youtu.be

**Comment by TheFlagCourier** [comment]
Exceptional submission.
Resolved.
